apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base-transformers

namespace: nginx

images:
- name: replaceme
  newName: nginx

namePrefix: nginx-

commonLabels:
    app: nginx
    run: nginx
    
patchesStrategicMerge:
- patch.yaml