apiVersion: v1
kind: Namespace
metadata:
  name: nginx

----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      run: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: nginx
spec:
  selector:
    app: nginx