apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: production-

commonLabels:
  variant: production
  org: acmeCorporation

commonAnnotations:
  note: Hello, I am production!

patchesStrategicMerge:
- deployment.yaml