apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base-hello

namePrefix: staging-

commonLabels:
  variant: staging
  org: acmeCorporation

commonAnnotations:
  note: Hello, I am staging!

patchesStrategicMerge:
- map.yaml