apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: cicd
  annotations:
    tekton.dev/git-0: https://github.com 
type: kubernetes.io/basic-auth
stringData:
  username: jporeilly
  password: Pentaho2020#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-push-service-account
  namespace: cicd
secrets:
  - name: basic-user-pass