apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ui
spec:
  rules:
  - host: argocd-dev.fake
    http:
      paths:
      - path: /
        backend:
          service
            name: argocd-server
          servicePort: htpps
  tls:
    - hosts:
        - argocd-dev.fake
      secretName: argocd-secret             