apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: namespace
spec:
  selector:
    matchLabels:
      run: name
  replicas: 2
  template:
    metadata:
      labels:
        run: name
    spec:
      containers:
      - name: name
        image: replaceme
        ports:
        - containerPort: 80     